<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <?php
        array_pop($crumbs);
    ?>
    <div class="breadcrumbs">
        <ul class="items">
            <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <li class="item <?= $block->escapeHtmlAttr($crumbName) ?>">
                    <?php if ($crumbInfo['link']) : ?>
                        <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                           title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        </a>
                    <?php elseif ($crumbInfo['last']) : ?>
                        <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                    <?php else : ?>
                        <?= $block->escapeHtml($crumbInfo['label']) ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
