<?php /*
<style>
    @font-face {
        font-display: swap;
        font-family: 'Roboto';
        src: url('<?= $block->getViewFileUrl('fonts/roboto/Roboto.woff2') ?>') format('woff2'),
        url('<?= $block->getViewFileUrl('fonts/roboto/Roboto.woff') ?>') format('woff'),
        url('<?= $block->getViewFileUrl('fonts/roboto/Roboto.ttf') ?>') format('truetype');
        font-weight: 400;
        font-style: normal;
    }

    @font-face {
        font-display: swap;
        font-family: 'Optimized Icons';
        src: url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Icons.woff2') ?>') format('woff2'),
        url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Icons.woff') ?>') format('woff'),
        url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Icons.ttf') ?>') format('truetype');
        font-weight: 400;
        font-style: normal;
    }
</style>
 */ ?>
