<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <div class="qty-dec" onclick="mfQtyDec()"></div>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
            <div class="qty-inc" onclick="mfQtyInc()" ></div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init-lazy" element="#product_addtocart_form">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script>

    function initAddForm() {
        let addFormInit = document.querySelector('[element="#product_addtocart_form"]');

        if (addFormInit) {
            addFormInit.setAttribute("type", "text/x-magento-init");

            require(['mage/apply/main'], function (mage) {
                if (mage) {
                    mage.apply('[element="#product_addtocart_form"]');
                }
            });
        }
    }

    document.querySelector('#product_addtocart_form').addEventListener('mouseover', initAddForm, {once: true});

    function mfQtyInc() {
        var q = document.getElementById('qty');
        if (q) {
            q.value = parseInt(q.value) + 1;
        }
    }

    function mfQtyDec() {
        var q = document.getElementById('qty');
        if (q) {
            q.value = parseInt(q.value) - 1;
            var qmin = <?= ($block->getMinimalQty($_product) * 1) ?? 1 ?>;
            if (q.value < qmin) q.value = qmin;
        }
    }
</script>
