<style>

    @font-face {
        font-family: 'Optimized-Theme-Icons';
        src:  url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Theme-Icons.eot') ?>');
        src:  url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Theme-Icons.eot#iefix') ?>') format('embedded-opentype'),
        url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Theme-Icons.ttf') ?>') format('truetype'),
        url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Theme-Icons.woff2') ?>') format('woff2'),
        url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Theme-Icons.woff') ?>') format('woff'),
        url('<?= $block->getViewFileUrl('fonts/Optimized/Optimized-Theme-Icons.svg#Optimized-Theme-Icons') ?>') format('svg');
        font-weight: normal;
        font-style: normal;
        font-display: block;
    }

</style>
